
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "piecraft"
version = "0.4.0"
description = "Minecraft-style pie chart generator"
dependencies = ["pillow"]
